[keyboard]
name = "rkey SosKey"
product_name = "rkey SosKey"
vendor_id = 0xfeed
product_id = 0x0505
manufacturer = "rkey-device"
chip = "stm32f303cc"

[matrix]
bootmagic = [0, 0]
row_pins = ["PB11", "PB14", "PB1", "PB0", "PA9", "PA3"]
col_pins = ["PB13", "PB12", "PB10", "PA10", "PA15", "PB3", "PB4", "PB5", "PB6", "PB7", "PB8", "PB9", "PA0", "PC15", "PA2", "PA1"]
row2col = true

[layout]
rows = 6
cols = 16
layers = 2
keymap = [
    [
        ["esc", "F1", "MO(1)", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F0", "F11", "MO(1)", "F12", "del"],
        ["grv", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "-", "=", "bspc", "Home"],
        ["Tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "lbrc", "rbrc", "bsls", "pgup"],
        ["caps", "A", "S", "D", "F", "G", "H", "J", "K", "L", ";", "'", "ent", "pgdn"],
        ["lsft", "Z", "X", "C", "V", "B", "N", "M", ",", ".", "slsh", "rsft", "Up", "End"],
        ["lctl", "lwin", "LAlt", "Space", "MO(1)", "RAlt", "rctl", "Left", "Down", "Right"]
    ],
    [
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ],
]
